st_length = input("Please type Length \n")
st_width = input("Please type width \n")
L = float(st_length)
W = float(st_width)
HM = input("How much for 1 meter? \n")
HMf = float(HM)
total = input("Total area is:")
print(L * W)
Pay = input("give the Guy :")
print(L * W * HMf)
